version: 0.2
phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - cd client && npm install
      - npm run build
      - cd .. && aws s3 cp --recursive --acl public-read ./client/build/. s3://$BUCKET_NAME/comic-counter/
      - aws s3 cp --acl public-read --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./client/build/index.html s3://$BUCKET_NAME/comic-counter/index.html
      - aws cloudfront create-invalidation --distribution-id $DIST_ID --paths /index.html
      - cd lambdas/leagueofcomicgeeks && npm install --omit=dev
      - cd .. && cp getReadCount.mjs index.mjs
      - zip code.zip index.mjs node_modules -r
      - aws lambda update-function-code --function-name $GET_READ_COUNT_ARN --zip-file fileb://code.zip
artifacts:
  files:
    - "**/*"